### ISSUE TITLE
Code is incompatible with Windows headers due to min()/max() preprocessor macros naming conflict

### ISSUE THREAD

**Issue by GiovanniDicanio** [dcleblanc/SafeInt#58] opened 2023-10-30 16:56 UTC
Code is incompatible with Windows headers that define the `min()` and `max()` macros.

(The issue is described in [this blog post](https://giodicanio.com/2023/10/20/beware-of-unsafe-conversions-from-size_t-to-int/), in the section titled _"Fixing an Ugly Situation of Naming Conflict with max"_).

An option is to embrace `std::numeric_limits<T>::max()` and `min()` with parentheses like this:

`(std::numeric_limits<T>::max)()`

This could be done just one time in a helper class template, and this class template could be used in the remaining code, e.g.:

```
template <typename T>
class SafeIntNumericLimits
{
public:
    static constexpr T Max() SAFEINT_NOTHROW
    {
        return (std::numeric_limits<T>::max)();
    }

    static constexpr T Min() SAFEINT_NOTHROW
    {
        return (std::numeric_limits<T>::min)();
    }
};
```
and then code could use the usual syntax (without the embracing parentheses):

```
SafeIntNumericLimits<T>::Max()
SafeIntNumericLimits<T>::Min()
```

(An alternative would be modifying every single call to `std::numeric_limits<T>::min()/max()` with the added parentheses.)

The attached code should fix the above issue (please note that the code requires more testing).
[SafeInt_GiovanniDicanio_2023_10_26.zip](https://github.com/dcleblanc/SafeInt/files/13207711/SafeInt_GiovanniDicanio_2023_10_26.zip)

**Comment by GiovanniDicanio** [comment] 2023-10-30 17:50
The code attached here should fix the above issue with explicit use of parentheses around `(std::numeric_limits<T>::min)()` and `(std::numeric_limits<T>::max)()`.

(Please note that the code requires more testing).
[SafeInt_GiovanniDicanio_2023_10_30.zip](https://github.com/dcleblanc/SafeInt/files/13208245/SafeInt_GiovanniDicanio_2023_10_30.zip)

**Comment by dcleblanc** [comment] 2023-10-30 17:51
Duplicate of #51

**Closed by dcleblanc** 2023-10-30 17:51 UTC
Labels: duplicate
